### ISSUE TITLE
How do I use this package with pdfkit?

### ISSUE THREAD

**Issue by xXxcb** [natancabral/pdfkit-table#48]
I have this bit of code below to that instantiates pdfkit... but I'd like to combine pdfkit with pdfkit table. Help??

```
return new Promise(async (resolve, reject) => {
            const doc = new PDFDocument({size: 'A4', margin: 40});
            const tbldoc = new PDFTable({size: doc.page.size, margin: doc.page.margins});
            doc.pipe(fs.createWriteStream('invoice.pdf'))

            this.row1(doc)
            this.row2( tbldoc )

            doc.end();
})
```

**Comment by tecoad** [comment]
how did you solve it?

**Comment by xXxcb** [comment]
@tecoad this package has pdf kit in it already you only need to use the table pieces as needed.

**Comment by catalinberta** [comment]
I think the problem here is that this package creates its own pdfkit instance internally and writes the tables to it. 
Rather, some (and I) have an instance already created with pdfkit and I'd like to use this package to write tables to an already existing document. Which, I think, is the general use case.
At first glance, it looks like this package does not allow you to supply the instance in this case.

I'll do some more digging and come back if there's a way, otherwise, I'll try to write it

**Comment by catalinberta** [comment]
> I'll do some more digging and come back if there's a way, otherwise, I'll try to write it

@tecoad @xXxcb 

I have managed to do this by replacing the page object.
Basically, if you have a pdfkit document already created and you'd like to use this package to write to it, then simply update the page object on the pdfkit-table instance with the one you want to render tables on. See example below:

```
import PDFDocument from "pdfkit";
import PDFDocumentWithTables from "pdfkit-table";

const pdfDoc = new PDFDocument({
      layout: "portrait",
      size: "A4"
    });

const tableDoc = new PDFDocumentWithTables(pdfDoc.options);
tableDoc.page = pdfDoc.page; // This updates the page which PDFDocumentWithTables will now draw on

const tableData = {
      title: "Title",
      subtitle: "Subtitle",
      headers: ["Country", "Conversion rate", "Trend"],
      rows: [
        ["Switzerland", "12%", "+1.12%"],
        ["France", "67%", "-0.98%"],
        ["England", "33%", "+4.44%"]
      ]
    };

tableDoc.table(tableData, {
      width: 300,
      x: 100,
      y: 600
    });

```

Not ideal, though it works.
